apiVersion: skaffold/v4beta10
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: salamapps/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
